* spacemacs module for doom emacs

Aim to port spacemacs features (keybindings, transient states, layers etc) to
doom, and provides a spacemacs module for doom emacs.

** Performance
I personally use it every day, and it works really great with doom.

*** Startup Time
Estimate that it costs around 0.2 ~ 0.3 second (but it depends what type of CPU you use).

** Clone the module
~git clone git@github.com:chenyanming/spacemacs_module_for_doom.git ~/.doom.d/modules/spacemacs~

If you want to clone to other directory, check the issue
https://github.com/chenyanming/spacemacs_module_for_doom/pull/2

** Enable necessary modules in ~init.el~
Make sure enable the necessary modules in ~init.el~.

At lease evil, org, gist, pdf, lookup, workspaces, eshell, and javascript etc.

In order to use the windows transient state properly, please add ~+numbers~ for
~windows-select~ module.
#+BEGIN_SRC emacs-lisp
(window-select     ; visually switch windows
        +numbers)
#+END_SRC

** Add missing packages in ~packages.el~
And install the missing packages in ~packages.el~

#+BEGIN_SRC emacs-lisp
(package! nov) ;; for epub layer
(package! auto-highlight-symbol) ;; for spacemacs-navigation
(package! eyebrowse) ;; for spacemacs-layouts
(package! bm) ;; for bm layer
(package! evil-iedit-state) ;; for spacemacs-navigation
(package! bind-map)
(package! symbol-overlay)
(package! move-text) ;; for spacemacs-editing
(package! string-inflection) ;; for spacemacs-editing
(package! forge) ;; for github layer
(package! evil-terminal-cursor-changer) ;; for spacemacs evil
(package! eshell-prompt-extras) ;; for shell layer
#+END_SRC
** IMPORTANT: Adjust ~+spacemacs~ based on your need
Since this package only simply load the necessary layer files and call their init functions, you can comment out
them in ~+spacemacs.el~ if necessary.

** Load the module in ~config.el~
~(load! "~/.doom.d/modules/spacemacs/+spacemacs")~

** Run ~./emacs.d/bin/doom sync~
Then sync the doom.

*Please notice*:
If you want to keep sync with my commits, every time you do git pull, you should better run ~./emacs.d/bin/doom
sync~ again, in case the ~packages.el~ is updated.

** Notes on transient states
Spacemacs's transient states are based on ~hydra~, while it seems has some
problems with doom. I am trying to fix it.
You can choose ~message~, ~lv~, or ~posframe~ on ~+spacemacs.el~
e.g. to choose ~posframe~:
#+BEGIN_SRC emacs-lisp
(setq hydra-hint-display-type 'posframe)
#+END_SRC


** Restart Emacs
Finally restart emacs~

Enjoy~

** Current status
1. Some Default spacemacs leader keybindings.
   - spacemacs-editing
   - spacemacs-layouts
   - spacemacs-navigation
   - spacemacs-defaults
   - spacemacs-evil
2. org layer keybindings.
3. Github layer keybindings.
4. PDF layer keybindings.
5. epub layer keybindings.
6. dash layer keybindings.
7. Some transient states:
   - Windows Transient State: ~SPC-w-.~
   - Symbol Overlay Transient State: ~SPC-s-o~
   - Symbol Highlight Transient State: ~SPC-s-h~
   - Buffer Transient State: ~SPC-b-.~
   - Error Transient State: ~SPC-e-.~
   - Font Scaling Transient State: ~SPC-z-x~
   - Frame Transparency Transient State: ~SPC-T-T~
   - Layouts Transient State: ~SPC-l~
   - Workspaces Transient State: ~SPC-l-w~
   - BM Transient State: ~SPC-a-b~
   - VCS Transient State: ~SPC-g-.~
   - Git Timemachine Transient State: ~SPC-g-t~
   - Move Text Transient State: ~SPC-x-J, SPC-x-K~
   - String Inflection Transient State: ~SPC-x-i-i~
   - Fold Transient State: ~SPC-z-.~
   - Evil number Transient State: ~SPC-n-+~
8. JavaScript layer major mode keybindings.
