* spacemacs_to_doom

Aim to port spacemacs features (keybindings, transient state, layers etc) to doom, and provides a spacemacs module for doom.

** Clone the module
~git clone git@github.com:chenyanming/spacemacs_module_for_doom.git ~/.doom.d/modules/spacemacs~

** Enable necessary modules in ~init.el~
Make sure enable the necessary modules in ~init.el~.

At lease org, gist, pdf, lookup, and workspaces

In order to use the windows transient state properly, please add ~+numbers~ for
~windows-select~ module.
#+BEGIN_SRC emacs-lisp
(window-select     ; visually switch windows
        +numbers)
#+END_SRC

** Add missing pacakges in ~packages.el~
And install the missing packages in ~packages.el~

#+BEGIN_SRC emacs-lisp
(package! nov) ;; for epub
(package! auto-highlight-symbol) ;; for spacemacs-navigation
(package! eyebrowse) ;; for spacemacs-layouts
#+END_SRC
** Adjust ~+spacemacs~ based on your need
Since this package only simply load the necessary layer files and call their init functions, you can comment out
them in ~+spacemacs.el~ if necessary.

** Load the module in ~config.el~
~(load! "~/.doom.d/modules/spacemacs/+spacemacs")~

** Run ~./emacs.d/bin/doom sync~
Then sync the doom.

*Please notice*:
If you want to keep sync with my commits, every time you do git pull, you should better run ~./emacs.d/bin/doom
sync~ again, in case the ~packages.el~ is updated.
** Notes on transient states
Spacemacs's transient states are based on ~hydra~, while it seems has some
problems with doom. I am trying to fix it.
You can choose ~message~, ~lv~, or ~posframe~ on ~+spacemacs.el~
e.g. to choose ~posframe~:
#+BEGIN_SRC emacs-lisp
(setq hydra-hint-display-type 'posframe)
#+END_SRC

** Restart Emacs
Finally restart emacs~

Enjoy~

** Current status
1. Default spacemacs leader keybindings.
2. org layer keybindings.
3. Github layer keybindings.
4. PDF layer keybindings.
5. epub layer keybindings.
6. dash layer keybindings.
7. Some transient states:
   - Windows Transient State: ~SPC-w-.~
   - Symbol Overlay Transient State: ~SPC-s-o~
   - Symbol Highlight Transient State: ~SPC-s-h~
   - Buffer Transient State: ~SPC-b-.~
   - Error Transient State: ~SPC-e-.~
   - Font Scaling Transient State: ~SPC-z-x~
   - Frame Transparency Transient State: ~SPC-T-T~
   - Layouts Transient State: ~SPC-l~
   - Workspaces Transient State: ~SPC-l-w~
