* spacemacs_to_doom

Aim to port spacemacs features (keybindings, transient state, layers etc) to doom, and provides a spacemacs module for doom.

** Clone the module
~git clone git@github.com:chenyanming/spacemacs_module_for_doom.git ~/.doom.d/modules/spacemacs~

** Enable necessary modules in ~init.el~
Make sure enable the necessary modules in ~init.el~.

At lease org, gist, pdf, and lookup

** Add missing pacakges in ~packages.el~
And install the missing packages in ~packages.el~

#+BEGIN_SRC emacs-lisp
(package! nov) ;; for epub
(package! ace-link) ;; for spacemacs-navigation
(package! ace-window) ;; for spacemacs-navigation
(package! auto-highlight-symbol) ;; for spacemacs-navigation
(package! centered-cursor-mode) ;; for spacemacs-navigation
(package! golden-ratio) ;; for spacemacs-navigation
(package! open-junk-file) ;; for spacemacs-navigation
(package! paradox) ;; for spacemacs-navigation
(package! restart-emacs) ;; for spacemacs-navigation
(package! symbol-overlay) ;; for spacemacs-navigation
(package! winum) ;; for spacemacs-navigation

#+END_SRC
** Load the module in ~config.el~
~(load! "~/.doom.d/modules/spacemacs/+spacemacs")~

** Run ~./emacs.d/bin/doom sync~
Then sync the doom.

*Please notice*:
If you want to keep sync with my commits, every time you do git pull, you should better run ~./emacs.d/bin/doom
sync~ again, in case the ~packages.el~ is updated.

** Restart Emacs
Finally restart emacs~

Enjoy~

** Current status
1. Default spacemacs leader keybindings.
2. Most org layer keybindings.
3. Github layer keybindings.
4. PDF layer keybindings.
5. epub layer keybindings.
5. dash layer keybindings.
6. Some transient states.
